### ISSUE TITLE
Syntax Error with Method "buildcomponent" Line 12

### ISSUE THREAD

**Issue by tai-bui1** [4d-depot/Build4D#3]
Hi,

Reported by a Partner on Discuss:
https://discuss.4d.com/t/error-when-executing-the-build-4d-component-buildcomponent-method/28194

I am not sure if it is a bug with 4D's parsing of the syntax, but it seems on Windows the following line due to the semicolon of the collection:
$targets:=(Is macOS) ?   ["x86_64_generic"; "arm64_macOS_lib"] : ["x86_64_generic"]

Seems like the issue does not occur if the following is performed:
$targets:=(Is macOS) ? New collection("x86_64_generic"; "arm64_macOS_lib") : ["x86_64_generic"]

or
$targets:=(Is Windows) ? ["x86_64_generic"] :  ["x86_64_generic"; "arm64_macOS_lib"]

Best Regards,
-Tai B.

**Comment by laurent-esnault** [comment]
moved to bugbase ACI0104087
